### ISSUE TITLE
New event link was not working

### ISSUE THREAD

**Issue by TJ-Support** [leegarner-glfusion/evlist#11]
Changed editevent=x to edit=x in admin index.php
Old Code:
`    if ($page == 'events') {
        $menu_arr[] = array('url' => EVLIST_ADMIN_URL . '/index.php?editevent=x',
            'text' => $LANG_EVLIST['new_event']);`
New Code:
`    if ($page == 'events') {
        $menu_arr[] = array('url' => EVLIST_ADMIN_URL . '/index.php?edit=x',
            'text' => $LANG_EVLIST['new_event']);`
[index.zip](https://github.com/leegarner-glfusion/evlist/files/762039/index.zip)

**Comment by leegarner** [comment]
Update the URL, thanks.
