### ISSUE TITLE
Categories did not save with dropdown

### ISSUE THREAD

**Issue by TJ-Support** [leegarner-glfusion/evlist#12]
Updated the editor and language files
editor.thtml
editor.uikit.thtml

Old Code:
```
      <span><strong>{$LANG_EVLIST['add_to_cats']}</strong>.</span>

          <select multiple name="categories">
```
New Code:
```
      <span>{$LANG_EVLIST['add_to_cats']}.</span>

          <select multiple name="categories[]">
```

english.php
english_utf-8.php

Old Code:
`'add_to_cats' => 'Add your event to a single or to multiple categories.',`
New Code:
`'add_to_cats' => '<strong>Add your event to a single or to multiple categories.</strong><br />To select more than one option in a multiple selection list, users can click options while holding down the CTRL key. A range can also be selected using the SHIFT key.',`

[categories.zip](https://github.com/leegarner-glfusion/evlist/files/768128/categories.zip)

**Comment by leegarner** [comment]
Thanks for the fix, changing to an array-type variable name works.
