### ISSUE TITLE
FIX for daily view not displaying the event times correctly

### ISSUE THREAD

**Issue by TJ-Support** [leegarner-glfusion/evlist#3]
{event_time} doesn't seem to be working in singleevent.thtml for dailyview.
A temporary fix for this is the following..
"Time Only Format" needs to be set to h:iA in the main site's configuration, Language and Locale settings. This also fixes the 24 hour time fault where 24 hour time shows AM and PM for event times.

**Comment by leegarner** [comment]
That is the appropriate fix. I'll check glFusion 1.4 but from at least 1.5 that format is the correct format for time_only. The next release of Evlist will not support glFusion below 1.6.0 so that shouldn't be an issue.
