### ISSUE TITLE
Ticket number changes when ticket is exported to Microsoft Excel

### ISSUE THREAD

**Issue by TJ-Support** [leegarner-glfusion/evlist#4]
There are two issues here related to the ticket number.

Example 1: The ticket number changes from 20161026125632644 to 20161026125632600

Example 2: When displayed in the cell of Micrsoft Excel worksheet, the ticket number looks like this.. 2.0161E+16.
The format of the ticket cell is set to general and may need to be set to number with no decimal places to display the full ticket number.

**Comment by leegarner** [comment]
I can't duplicate example 1, both printed and exported tickets have the same ID

That's normal for MS Excel. I added letters to the beginning of ticket numbers so they'll be interpreted as strings.

**Comment by TJ-Support** [comment]
The latest commit has fixed this issue when new ticket registrations are made. (Old tickets remain the same). Thank you Lee.
