### ISSUE TITLE
Missing t in Language file

### ISSUE THREAD

**Issue by TJ-Support** [leegarner-glfusion/evlist#6]
Missing t found in language file
`haven&apos;t`

`    'tickettypes' => 'Tickets can be created for free or paid admission, and to cover one event occurrence or all occurrences (event pass). Tickets are only used if the global &quot;Enable RSVP&quot; setting is enabled.<br />Ticket Types can only be deleted if they haven&apos;t been used for any events.',
),`

**Comment by leegarner** [comment]
Fixed in source
