### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by matrox66** [leegarner-glfusion/evlist#8]
Missing Translation:
event.thtml                   line 227               "Register"
event.uikit.thtml           line 285               "Register"
editor.thtml                  line 825-828        "Allow Ticket Printing?:","No","Paid Only","Paid or Unpaid"
editor.uikit.thtml          line 836-840        "Allow Ticket Printing?:","No","Paid Only","Paid or Unpaid"

Changing the "rec_periods" in Language Files from Day to Day(s), Week to Week(s) ....
and deleting the (s) in:
editor.thtml                 line 189,201,213,225,237
editor.uikit.thtml         line 186,198,210,222,234
evEvent.class.php        line 987,1773

**Comment by leegarner** [comment]
Updated language strings
